
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  CpuComponent: typeof import("../../app/components/Cpu/CpuComponent.vue")['default']
  CpuSubCpuComponent: typeof import("../../app/components/Cpu/SubCpuComponent.vue")['default']
  DiskComponent: typeof import("../../app/components/Disk/DiskComponent.vue")['default']
  GlobalDataComponent: typeof import("../../app/components/GlobalData/GlobalDataComponent.vue")['default']
  MemoryComponent: typeof import("../../app/components/Memory/MemoryComponent.vue")['default']
  MemorySubMemoryComponent: typeof import("../../app/components/Memory/SubMemoryComponent.vue")['default']
  NetworkComponent: typeof import("../../app/components/Network/NetworkComponent.vue")['default']
  Sidebar: typeof import("../../app/components/ui/sidebar/index")['Sidebar']
  ThemeToggle: typeof import("../../app/components/ThemeToggle.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  AlertDialog: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialog']
  AlertDialogAction: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogAction']
  AlertDialogCancel: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogCancel']
  AlertDialogContent: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogContent']
  AlertDialogDescription: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogDescription']
  AlertDialogFooter: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogFooter']
  AlertDialogHeader: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogHeader']
  AlertDialogTitle: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTitle']
  AlertDialogTrigger: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTrigger']
  Button: typeof import("../../app/components/ui/button/index")['Button']
  Card: typeof import("../../app/components/ui/card/index")['Card']
  CardAction: typeof import("../../app/components/ui/card/index")['CardAction']
  CardContent: typeof import("../../app/components/ui/card/index")['CardContent']
  CardDescription: typeof import("../../app/components/ui/card/index")['CardDescription']
  CardFooter: typeof import("../../app/components/ui/card/index")['CardFooter']
  CardHeader: typeof import("../../app/components/ui/card/index")['CardHeader']
  CardTitle: typeof import("../../app/components/ui/card/index")['CardTitle']
  Checkbox: typeof import("../../app/components/ui/checkbox/index")['Checkbox']
  DropdownMenu: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenu']
  DropdownMenuCheckboxItem: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
  DropdownMenuContent: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuContent']
  DropdownMenuGroup: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']
  DropdownMenuItem: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuItem']
  DropdownMenuLabel: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']
  DropdownMenuRadioGroup: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
  DropdownMenuRadioItem: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
  DropdownMenuSeparator: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']
  DropdownMenuShortcut: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']
  DropdownMenuSub: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSub']
  DropdownMenuSubContent: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']
  DropdownMenuSubTrigger: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
  DropdownMenuTrigger: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']
  DropdownMenuPortal: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']
  Input: typeof import("../../app/components/ui/input/index")['Input']
  Label: typeof import("../../app/components/ui/label/index")['Label']
  Progress: typeof import("../../app/components/ui/progress/index")['Progress']
  Select: typeof import("../../app/components/ui/select/index")['Select']
  SelectContent: typeof import("../../app/components/ui/select/index")['SelectContent']
  SelectGroup: typeof import("../../app/components/ui/select/index")['SelectGroup']
  SelectItem: typeof import("../../app/components/ui/select/index")['SelectItem']
  SelectItemText: typeof import("../../app/components/ui/select/index")['SelectItemText']
  SelectLabel: typeof import("../../app/components/ui/select/index")['SelectLabel']
  SelectScrollDownButton: typeof import("../../app/components/ui/select/index")['SelectScrollDownButton']
  SelectScrollUpButton: typeof import("../../app/components/ui/select/index")['SelectScrollUpButton']
  SelectSeparator: typeof import("../../app/components/ui/select/index")['SelectSeparator']
  SelectTrigger: typeof import("../../app/components/ui/select/index")['SelectTrigger']
  SelectValue: typeof import("../../app/components/ui/select/index")['SelectValue']
  Sheet: typeof import("../../app/components/ui/sheet/index")['Sheet']
  SheetClose: typeof import("../../app/components/ui/sheet/index")['SheetClose']
  SheetContent: typeof import("../../app/components/ui/sheet/index")['SheetContent']
  SheetDescription: typeof import("../../app/components/ui/sheet/index")['SheetDescription']
  SheetFooter: typeof import("../../app/components/ui/sheet/index")['SheetFooter']
  SheetHeader: typeof import("../../app/components/ui/sheet/index")['SheetHeader']
  SheetTitle: typeof import("../../app/components/ui/sheet/index")['SheetTitle']
  SheetTrigger: typeof import("../../app/components/ui/sheet/index")['SheetTrigger']
  SidebarContent: typeof import("../../app/components/ui/sidebar/index")['SidebarContent']
  SidebarFooter: typeof import("../../app/components/ui/sidebar/index")['SidebarFooter']
  SidebarGroup: typeof import("../../app/components/ui/sidebar/index")['SidebarGroup']
  SidebarGroupAction: typeof import("../../app/components/ui/sidebar/index")['SidebarGroupAction']
  SidebarGroupContent: typeof import("../../app/components/ui/sidebar/index")['SidebarGroupContent']
  SidebarGroupLabel: typeof import("../../app/components/ui/sidebar/index")['SidebarGroupLabel']
  SidebarHeader: typeof import("../../app/components/ui/sidebar/index")['SidebarHeader']
  SidebarInput: typeof import("../../app/components/ui/sidebar/index")['SidebarInput']
  SidebarInset: typeof import("../../app/components/ui/sidebar/index")['SidebarInset']
  SidebarMenu: typeof import("../../app/components/ui/sidebar/index")['SidebarMenu']
  SidebarMenuAction: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuAction']
  SidebarMenuBadge: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuBadge']
  SidebarMenuButton: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuButton']
  SidebarMenuItem: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuItem']
  SidebarMenuSkeleton: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSkeleton']
  SidebarMenuSub: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSub']
  SidebarMenuSubButton: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubButton']
  SidebarMenuSubItem: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubItem']
  SidebarProvider: typeof import("../../app/components/ui/sidebar/index")['SidebarProvider']
  SidebarRail: typeof import("../../app/components/ui/sidebar/index")['SidebarRail']
  SidebarSeparator: typeof import("../../app/components/ui/sidebar/index")['SidebarSeparator']
  SidebarTrigger: typeof import("../../app/components/ui/sidebar/index")['SidebarTrigger']
  Skeleton: typeof import("../../app/components/ui/skeleton/index")['Skeleton']
  Table: typeof import("../../app/components/ui/table/index")['Table']
  TableBody: typeof import("../../app/components/ui/table/index")['TableBody']
  TableCaption: typeof import("../../app/components/ui/table/index")['TableCaption']
  TableCell: typeof import("../../app/components/ui/table/index")['TableCell']
  TableEmpty: typeof import("../../app/components/ui/table/index")['TableEmpty']
  TableFooter: typeof import("../../app/components/ui/table/index")['TableFooter']
  TableHead: typeof import("../../app/components/ui/table/index")['TableHead']
  TableHeader: typeof import("../../app/components/ui/table/index")['TableHeader']
  TableRow: typeof import("../../app/components/ui/table/index")['TableRow']
  Tooltip: typeof import("../../app/components/ui/tooltip/index")['Tooltip']
  TooltipContent: typeof import("../../app/components/ui/tooltip/index")['TooltipContent']
  TooltipProvider: typeof import("../../app/components/ui/tooltip/index")['TooltipProvider']
  TooltipTrigger: typeof import("../../app/components/ui/tooltip/index")['TooltipTrigger']
  Separator: typeof import("../../app/components/ui/separator/index")['Separator']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyCpuComponent: LazyComponent<typeof import("../../app/components/Cpu/CpuComponent.vue")['default']>
  LazyCpuSubCpuComponent: LazyComponent<typeof import("../../app/components/Cpu/SubCpuComponent.vue")['default']>
  LazyDiskComponent: LazyComponent<typeof import("../../app/components/Disk/DiskComponent.vue")['default']>
  LazyGlobalDataComponent: LazyComponent<typeof import("../../app/components/GlobalData/GlobalDataComponent.vue")['default']>
  LazyMemoryComponent: LazyComponent<typeof import("../../app/components/Memory/MemoryComponent.vue")['default']>
  LazyMemorySubMemoryComponent: LazyComponent<typeof import("../../app/components/Memory/SubMemoryComponent.vue")['default']>
  LazyNetworkComponent: LazyComponent<typeof import("../../app/components/Network/NetworkComponent.vue")['default']>
  LazySidebar: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['Sidebar']>
  LazyThemeToggle: LazyComponent<typeof import("../../app/components/ThemeToggle.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyAlertDialog: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialog']>
  LazyAlertDialogAction: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogAction']>
  LazyAlertDialogCancel: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogCancel']>
  LazyAlertDialogContent: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogContent']>
  LazyAlertDialogDescription: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogDescription']>
  LazyAlertDialogFooter: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogFooter']>
  LazyAlertDialogHeader: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogHeader']>
  LazyAlertDialogTitle: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTitle']>
  LazyAlertDialogTrigger: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTrigger']>
  LazyButton: LazyComponent<typeof import("../../app/components/ui/button/index")['Button']>
  LazyCard: LazyComponent<typeof import("../../app/components/ui/card/index")['Card']>
  LazyCardAction: LazyComponent<typeof import("../../app/components/ui/card/index")['CardAction']>
  LazyCardContent: LazyComponent<typeof import("../../app/components/ui/card/index")['CardContent']>
  LazyCardDescription: LazyComponent<typeof import("../../app/components/ui/card/index")['CardDescription']>
  LazyCardFooter: LazyComponent<typeof import("../../app/components/ui/card/index")['CardFooter']>
  LazyCardHeader: LazyComponent<typeof import("../../app/components/ui/card/index")['CardHeader']>
  LazyCardTitle: LazyComponent<typeof import("../../app/components/ui/card/index")['CardTitle']>
  LazyCheckbox: LazyComponent<typeof import("../../app/components/ui/checkbox/index")['Checkbox']>
  LazyDropdownMenu: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenu']>
  LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
  LazyDropdownMenuContent: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuContent']>
  LazyDropdownMenuGroup: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']>
  LazyDropdownMenuItem: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuItem']>
  LazyDropdownMenuLabel: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']>
  LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
  LazyDropdownMenuRadioItem: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
  LazyDropdownMenuSeparator: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
  LazyDropdownMenuShortcut: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
  LazyDropdownMenuSub: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSub']>
  LazyDropdownMenuSubContent: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
  LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
  LazyDropdownMenuTrigger: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
  LazyDropdownMenuPortal: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']>
  LazyInput: LazyComponent<typeof import("../../app/components/ui/input/index")['Input']>
  LazyLabel: LazyComponent<typeof import("../../app/components/ui/label/index")['Label']>
  LazyProgress: LazyComponent<typeof import("../../app/components/ui/progress/index")['Progress']>
  LazySelect: LazyComponent<typeof import("../../app/components/ui/select/index")['Select']>
  LazySelectContent: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectContent']>
  LazySelectGroup: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectGroup']>
  LazySelectItem: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectItem']>
  LazySelectItemText: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectItemText']>
  LazySelectLabel: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectLabel']>
  LazySelectScrollDownButton: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectScrollDownButton']>
  LazySelectScrollUpButton: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectScrollUpButton']>
  LazySelectSeparator: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectSeparator']>
  LazySelectTrigger: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectTrigger']>
  LazySelectValue: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectValue']>
  LazySheet: LazyComponent<typeof import("../../app/components/ui/sheet/index")['Sheet']>
  LazySheetClose: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetClose']>
  LazySheetContent: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetContent']>
  LazySheetDescription: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetDescription']>
  LazySheetFooter: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetFooter']>
  LazySheetHeader: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetHeader']>
  LazySheetTitle: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetTitle']>
  LazySheetTrigger: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetTrigger']>
  LazySidebarContent: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarContent']>
  LazySidebarFooter: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarFooter']>
  LazySidebarGroup: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroup']>
  LazySidebarGroupAction: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupAction']>
  LazySidebarGroupContent: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupContent']>
  LazySidebarGroupLabel: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupLabel']>
  LazySidebarHeader: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarHeader']>
  LazySidebarInput: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarInput']>
  LazySidebarInset: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarInset']>
  LazySidebarMenu: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenu']>
  LazySidebarMenuAction: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuAction']>
  LazySidebarMenuBadge: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuBadge']>
  LazySidebarMenuButton: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuButton']>
  LazySidebarMenuItem: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuItem']>
  LazySidebarMenuSkeleton: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSkeleton']>
  LazySidebarMenuSub: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSub']>
  LazySidebarMenuSubButton: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubButton']>
  LazySidebarMenuSubItem: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubItem']>
  LazySidebarProvider: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarProvider']>
  LazySidebarRail: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarRail']>
  LazySidebarSeparator: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarSeparator']>
  LazySidebarTrigger: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarTrigger']>
  LazySkeleton: LazyComponent<typeof import("../../app/components/ui/skeleton/index")['Skeleton']>
  LazyTable: LazyComponent<typeof import("../../app/components/ui/table/index")['Table']>
  LazyTableBody: LazyComponent<typeof import("../../app/components/ui/table/index")['TableBody']>
  LazyTableCaption: LazyComponent<typeof import("../../app/components/ui/table/index")['TableCaption']>
  LazyTableCell: LazyComponent<typeof import("../../app/components/ui/table/index")['TableCell']>
  LazyTableEmpty: LazyComponent<typeof import("../../app/components/ui/table/index")['TableEmpty']>
  LazyTableFooter: LazyComponent<typeof import("../../app/components/ui/table/index")['TableFooter']>
  LazyTableHead: LazyComponent<typeof import("../../app/components/ui/table/index")['TableHead']>
  LazyTableHeader: LazyComponent<typeof import("../../app/components/ui/table/index")['TableHeader']>
  LazyTableRow: LazyComponent<typeof import("../../app/components/ui/table/index")['TableRow']>
  LazyTooltip: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['Tooltip']>
  LazyTooltipContent: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipContent']>
  LazyTooltipProvider: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipProvider']>
  LazyTooltipTrigger: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipTrigger']>
  LazySeparator: LazyComponent<typeof import("../../app/components/ui/separator/index")['Separator']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
